### ISSUE TITLE
Why do not use maxpool layer?

### ISSUE THREAD

**Issue by JungHunOh** [serdarozsoy/corinfomax-ssl#4]
Hello, Thank you for the motivating work!
I wonder why the maxpool layer in the original resnet18 model is removed in this code ([link](https://github.com/serdarozsoy/corinfomax-ssl/blob/c0b917ebbf80ad272f62da398b3f1c05245a89bf/cifars-tiny/model_base_resnet.py#L18)).
I think it can lead to significant performance improvement.
Thanks.

**Comment by serdarozsoy** [comment]
Thank you for your expressed interest. Modified ResNet-18 version (changes in the first convolutional layer and the removal of the maxpool layer) is widely used for CIFAR datasets to handle lower resolution images (32x32). 

Other benchmarked results for CIFAR datasets also used this version, according to their papers and codebases. All these details are also provided in Section 5.1.2 and Appendix F of our paper.
