### ISSUE TITLE
Inconsistent Baseline Results on ImageNet

### ISSUE THREAD

**Issue by tianbao-anw** [serdarozsoy/corinfomax-ssl#6]
The reported linear evaluation accuracy for BYOL (69.3%) and VICReg (68.6%) on ImageNet appears significantly lower than the results reported in their respective original papers (74.3% and 73.2%). 

Is this because there is a difference in the implementation?

**Comment by serdarozsoy** [comment]
You are referring to the results in Table 1. 

Firstly, all results in that table, except ours, are directly taken from other papers.

While the values you are referring to from the original papers correspond to results obtained after 1000 pretraining epochs, the experiments on ImageNet-1K in our paper were conducted with 100 pretraining epochs, as mentioned in Section 5.1.3.  Similarly, the results for BYOL, Barlow Twins, and VICReg with 100 pretraining epochs are cited from Table 5 of the VICReg paper.

Therefore, there is no difference in the implementation or any inconsistency in the baseline results.

**Comment by tianbao-anw** [comment]
Oh, I see. Thank you very much for your patience.
